/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_EnergyComputationAlgoNative */

#ifndef _Included_application_EnergyComputationAlgoNative
#define _Included_application_EnergyComputationAlgoNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     application_EnergyComputationAlgoNative
 * Method:    computeWifiEnergy
 * Signature: ([[DII)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_application_EnergyComputationAlgoNative_computeWifiEnergy
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
